# docker compose for an nginx with php-fpm container in the same network
version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - gopapi-api
    networks:
      - gopapi-network
  gopapi-api:
    hostname: api.gopapi.localhost
    build: 
      context: ${GOPAPI_DIR-..}/gopapi-api
    container_name: gopapi-api
    restart: always
    environment:
      - AUTH0_DOMAIN=dev-r4rgf3uh.us.auth0.com
      - AUTH0_AUDIENCE=gopapi-api
      - APP_ENV=development
    volumes:
      - ${GOPAPI_DIR-..}/gopapi-api/src:/var/www/html
    networks:
      - gopapi-network
networks:
  gopapi-network:
    driver: bridge