# docker compose for an nginx with php-fpm container in the same network
version: '3.9'
services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 4443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certificates:/var/local/step:ro
    depends_on:
      - gopapi-api
    networks:
      - gopapi-network

  gopapi-api:
    hostname: api.gopapi.localhost
    build: 
      context: ${GOPAPI_DIR-..}/gopapi-api
    container_name: gopapi-api
    restart: always
    environment:
      - AUTH0_DOMAIN=dev-r4rgf3uh.us.auth0.com
      - AUTH0_AUDIENCE=gopapi-api
      - APP_ENV=development
    volumes:
      - ${GOPAPI_DIR-..}/gopapi-api/src:/var/www/html
    networks:
      - gopapi-network

  gopapi-ca:
    build:
      context: ${GOPAPI_DIR-..}/gopapi-ca
    container_name: gopapi-ca
    restart: always
    ports:
      - 8443:8443
    networks:
      - gopapi-network
  
  gopapi-renewer:
    depends_on:
      - gopapi-ca
    build:
      context: ${GOPAPI_DIR-..}/gopapi-renewer
    volumes:
      - certificates:/var/local/step
    secrets:
      - password
    environment:
      STEPPATH: /home/step
      STEP_CA_URL: https://gopapi-ca
      STEP_FINGERPRINT: 84a033e84196f73bd593fad7a63e509e57fd982f02084359c4e8c5c864efc27d
      STEP_ROOT: /var/local/step/root_ca.crt
      STEP_KID: DmAtZt2EhmZr_iTJJ387fr4Md2NbzMXGdXQNW1UWPXk
      STEP_PASSWORD_FILE: /run/secrets/password
      COMMON_NAME: nginx
    networks:
      - gopapi-network

volumes:
  certificates:


secrets:
  password:
    file: ./password.txt

networks:
  gopapi-network:
    driver: bridge